package com.example.myapp.event;

/** Event shell — generated by the Fluxtion project starter. */
public final class PriceUpdate implements com.telamin.fluxtion.runtime.event.Event {
    private final String symbol;
    private final double price;
    private final int filterId;

    /** Default filter for the generated example; use the full constructor to select another route. */
    public PriceUpdate(String symbol, double price) {
        this(symbol, price, 7);
    }


    public PriceUpdate(String symbol, double price, int filterId) {
        this.symbol = symbol;
        this.price = price;
        this.filterId = filterId;
    }

    public String symbol() {
        return symbol;
    }

    public double price() {
        return price;
    }

    public int filterId() {
        return filterId;
    }

    @Override
    public String toString() {
        return "PriceUpdate{" + "symbol=" + symbol + ", " + "price=" + price + ", " + "filterId=" + filterId + "}";
    }
}
