package com.example.myapp.builder;

import com.telamin.fluxtion.runtime.DataFlow;

import java.util.function.Supplier;

/**
 * Builds the hosted Fluxtion graph for Mongoose. Referenced from config/server-config.yml
 * (eventHandlerBuilder:). MyProcessor is AOT-generated by ./generate.sh and loaded reflectively.
 * Audit routing is NOT done here: Mongoose replaces the processor's audit listener with the one
 * given to MongooseServer.bootServer (see MongooseMain).
 */
public class MyProcessorSupplier implements Supplier<DataFlow> {

    @Override
    public DataFlow get() {
        DataFlow flow;
        try {
            flow = (DataFlow) Class.forName("com.example.myapp.generated.MyProcessor")
                    .getDeclaredConstructor().newInstance();
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException("generated processor not found — run ./generate.sh", e);
        }
        flow.setUnKnownEventHandler(e -> System.out.println(
                "unhandled event (no @OnEventHandler matched — check the feed valueMapper): " + e));
        return flow;
    }
}
