package com.example.riskflow.node;

import com.telamin.fluxtion.runtime.annotations.OnTrigger;
import com.telamin.fluxtion.runtime.annotations.runtime.ServiceRegistered;
import com.telamin.fluxtion.runtime.output.MessageSink;

/**
 * Trigger node — generated by the Fluxtion project starter. References Risk and fires {@code @OnTrigger} after it updates, publishing the latest event to the "audit" sink.
 */
public class Audit {

    private final Risk risk;
    private Object latestEvent;

    public Audit(Risk risk) {
        this.risk = risk;
    }

    /** "audit" output sink, injected via @ServiceRegistered (null until registered). */
    public MessageSink<Object> auditSink;

    @ServiceRegistered
    @SuppressWarnings({"unchecked", "rawtypes"})
    public void onSink(MessageSink sink, String name) {
        if ("audit".equals(name)) {
            this.auditSink = sink;
            return;
        }
    }

    /** Most recent event seen; read by downstream nodes on trigger. */
    public Object getLatestEvent() {
        return latestEvent;
    }

    @OnTrigger
    public boolean onAudit() {
        Object event = risk.getLatestEvent();
        this.latestEvent = event;
        if (auditSink != null) {
            auditSink.accept(event); // publish to the "audit" sink
        }
        // TODO: react to the updated Risk state
        return true;
    }
}
