package com.example.riskflow.node;

import com.telamin.fluxtion.runtime.annotations.OnTrigger;
import com.telamin.fluxtion.runtime.annotations.OnEventHandler;
import com.example.riskflow.event.*;

/**
 * Trigger node — generated by the Fluxtion project starter. References RootNode and fires {@code @OnTrigger} after it updates; handles OrderEvent via {@code @OnEventHandler}.
 */
public class Enrich {

    private final RootNode rootNode;
    private Object latestEvent;

    public Enrich(RootNode rootNode) {
        this.rootNode = rootNode;
    }

    /** Most recent event seen; read by downstream nodes on trigger. */
    public Object getLatestEvent() {
        return latestEvent;
    }

    @OnEventHandler
    public boolean onOrderEvent(OrderEvent event) {
        this.latestEvent = event;
        // TODO: handle OrderEvent
        return true;
    }
    @OnTrigger
    public boolean onEnrich() {
        Object event = rootNode.getLatestEvent();
        this.latestEvent = event;
        // TODO: react to the updated RootNode state
        return true;
    }
}
