package com.example.riskflow.node;

import com.telamin.fluxtion.runtime.annotations.OnTrigger;
import com.telamin.fluxtion.runtime.annotations.OnEventHandler;
import com.example.riskflow.event.*;
import com.telamin.fluxtion.runtime.annotations.runtime.ServiceRegistered;
import com.telamin.fluxtion.runtime.output.MessageSink;

/**
 * Trigger node — generated by the Fluxtion project starter. References RootNode, Enrich and fires {@code @OnTrigger} after any of them update; handles PriceUpdate via {@code @OnEventHandler}, publishing the latest event to the "alerts" sink.
 */
public class Risk {

    private final RootNode rootNode;
    private final Enrich enrich;
    private Object latestEvent;

    public Risk(RootNode rootNode, Enrich enrich) {
        this.rootNode = rootNode;
        this.enrich = enrich;
    }

    /** "alerts" output sink, injected via @ServiceRegistered (null until registered). */
    public MessageSink<Object> alertsSink;

    @ServiceRegistered
    @SuppressWarnings({"unchecked", "rawtypes"})
    public void onSink(MessageSink sink, String name) {
        if ("alerts".equals(name)) {
            this.alertsSink = sink;
            return;
        }
    }

    /** Most recent event seen; read by downstream nodes on trigger. */
    public Object getLatestEvent() {
        return latestEvent;
    }

    @OnEventHandler
    public boolean onPriceUpdate(PriceUpdate event) {
        this.latestEvent = event;
        if (alertsSink != null) {
            alertsSink.accept(event); // publish to the "alerts" sink
        }
        // TODO: handle PriceUpdate
        return true;
    }
    @OnTrigger
    public boolean onRisk() {
        Object event = rootNode.getLatestEvent();
        this.latestEvent = event;
        if (alertsSink != null) {
            alertsSink.accept(event); // publish to the "alerts" sink
        }
        // TODO: react to the updated RootNode state (also references Enrich)
        return true;
    }
}
