package com.example.myapp.node;

import com.example.myapp.event.*;
import com.telamin.fluxtion.runtime.annotations.OnEventHandler;
import com.telamin.fluxtion.runtime.audit.EventLogNode;

/**
 * The event-handler node — generated by the Fluxtion project starter.
 * One {@code @OnEventHandler} per declared event type.
 * Extends EventLogNode so each handler can audit via {@code auditLog}.
 * Stores the latest event; Child reacts downstream via {@code @OnTrigger}.
 */
public class RootNode extends EventLogNode {

    /** Most recent event handled; read by Child on trigger. */
    private Object latestEvent;

    public Object getLatestEvent() {
        return latestEvent;
    }

    @com.telamin.fluxtion.runtime.annotations.OnEventHandler(filterId = 7, propagate = true)
@javax.annotation.processing.Generated("fluxtion-starter")
    
    public boolean onPriceUpdate(PriceUpdate event) {
        auditLog.info("receivedEvent", event);
        auditLog.info("price", event.price());
        this.latestEvent = event;
        // TODO: handle PriceUpdate
        return true; // propagate to downstream nodes
    }
}
