package com.example.myapp;

import com.example.myapp.event.*;
import com.example.myapp.generated.MyProcessor;
import com.telamin.fluxtion.runtime.DataFlow;

/**
 * Entry point — generated by the Fluxtion project starter.
 * AOT: MyProcessor is generated at build time by the
 * fluxtion-maven-plugin (springToFluxtion, from application-context.xml) — the shell is overwritten by './mvnw package'.
 */
public final class FluxtionMain {

    public static void main(String[] args) {
        DataFlow flow = new MyProcessor();
        flow.init();
        // Surface any event that reaches no @OnEventHandler (handy while wiring a new graph — e.g. a
        // raw String with no handler). Without this it is silently dropped.
        flow.setUnKnownEventHandler(e -> System.out.println(
                "unhandled event (no @OnEventHandler matched — add a handler): " + e));
        // Print audit records to stdout — the default java.util.logging sink is invisible in the
        // Playground console, so an audited graph would otherwise look idle.
        flow.setAuditLogProcessor(logRecord -> System.out.println(logRecord));

        flow.onEvent(new PriceUpdate("demo", 1.0));

        System.out.println("FluxtionMain: processed sample events");
    }
}
