package telamin.fluxtion.audit.analyser.analyser.ui;
import javax.swing.*;import java.awt.*;import java.awt.image.*;import java.nio.file.*;import java.util.List;import java.util.Map;import java.util.Set;
import telamin.fluxtion.audit.analyser.analyser.design.*;
import telamin.fluxtion.audit.analyser.analyser.graph.*;
import telamin.fluxtion.audit.analyser.analyser.parse.*;
import telamin.fluxtion.audit.analyser.analyser.filter.*;
import telamin.fluxtion.audit.analyser.analyser.report.*;
import telamin.fluxtion.audit.analyser.analyser.template.*;
public class SurfaceProbe {
 static Path out;static JFrame f;
 static void show(JComponent c,String name,int w,int h)throws Exception{WorkspaceProbe.edt(()->{f.setContentPane(c);f.setSize(w,h);f.validate();f.setVisible(true);return null;});for(int i=0;i<4;i++){new Robot().waitForIdle();WorkspaceProbe.edt(()->{f.validate();return null;});}WorkspaceProbe.edt(()->{save(f,name);return null;});}
 static void save(Component c,String n)throws Exception{BufferedImage b=new BufferedImage(c.getWidth(),c.getHeight(),BufferedImage.TYPE_INT_RGB);Graphics2D g=b.createGraphics();c.paint(g);g.dispose();javax.imageio.ImageIO.write(b,"png",out.resolve(n+".png").toFile());}
 public static void main(String[] args)throws Exception{out=Path.of(args[0]);System.setProperty("user.home",Files.createDirectories(out.resolve("home-surfaces")).toString());try{
  WorkspaceProbe.edt(()->{com.formdev.flatlaf.FlatLightLaf.setup();f=new JFrame("DEMO review");f.setLocation(40,40);return null;});
  var finding=new ProducerResult.Finding("DEMO_RULE","WARNING","A binding is missing","The DEMO handler cannot run.","Add the DEMO binding.",Map.of("kind","UNKNOWN","xmlDeclaration","<bean id='DEMO'/>"),Map.of(),List.of());
  var result=new ProducerResult("DEMO-result.json","validate","","",List.of(finding),Map.of(),Map.of());
  ProducerFindingsPanel findings=WorkspaceProbe.edt(()->{var p=new ProducerFindingsPanel();p.render(result,null,null,null,"",loc->{});return p;});show(findings,"findings-light",450,650);show(findings,"findings-220",220,650);System.out.println("finding code="+WorkspaceProbe.edt(()->WorkspaceProbe.all(findings).stream().filter(c->c instanceof JLabel a&&a.getText().equals("DEMO_RULE")).map(c->c.getBounds()+" visible="+((JComponent)c).getVisibleRect()).toList())); System.out.println("narrow findings text="+WorkspaceProbe.edt(()->WorkspaceProbe.all(findings).stream().filter(c->c instanceof JTextArea a&&a.getText().equals("A binding is missing")).map(c->c.getBounds()+" visible="+((JComponent)c).getVisibleRect()).toList()));
  WorkspaceProbe.edt(()->{com.formdev.flatlaf.FlatDarkLaf.setup();SwingUtilities.updateComponentTreeUI(f);findings.render(result,null,null,null,"",loc->{});return null;});show(findings,"findings-dark",450,650);
  WorkspaceProbe.edt(()->{com.formdev.flatlaf.FlatLightLaf.setup();return null;});
  ChartPanel chart=WorkspaceProbe.edt(()->{var p=new ChartPanel();Series s=new Series("DEMO counts");s.add(1003,10);s.add(31003,17);s.add(61003,20);p.setSeries(List.of(s));return p;});show(chart,"chart-round",640,400);
  GraphTabs graphs=WorkspaceProbe.edt(()->{var p=new GraphTabs();p.bind(new HeapLogStore(Samples.sample()),new FilterState());p.addGraph("DEMO second");return p;});show(graphs,"graphs-narrow",330,600);
  WorkspaceProbe.edt(()->{for(Component c:WorkspaceProbe.all(graphs.graphNamed("DEMO second")))if(c instanceof JToggleButton b&&b.getToolTipText()!=null&&b.getToolTipText().startsWith("Show the Series")){b.doClick();break;}return null;});show(graphs,"series-editor-narrow",330,600);System.out.println("series editor controls="+WorkspaceProbe.edt(()->WorkspaceProbe.all(graphs.graphNamed("DEMO second")).stream().filter(c->c instanceof JButton b&&List.of("Add","Pick…").contains(b.getText())).map(c->((JButton)c).getText()+" "+c.getBounds()+" visible="+((JComponent)c).getVisibleRect()).toList()));
  var walk=new telamin.fluxtion.audit.analyser.analyser.walk.WalkSpec("DEMO tour","DEMO tour","DEMO","","",null,List.of(),DemoTour.steps(),Map.of());
  WalksPanel walks=WorkspaceProbe.edt(()->{var p=new WalksPanel(()->List.of(walk),params->telamin.fluxtion.audit.analyser.analyser.llm.ActionResult.ok("walk","ok",Map.of()),List::of);p.refresh();return p;});show(walks,"walks-narrow",220,600);System.out.println("walk controls="+WorkspaceProbe.edt(()->WorkspaceProbe.all(walks).stream().filter(c->c instanceof JButton).map(c->((JButton)c).getText()+" "+c.getBounds()+" parent="+c.getParent().getBounds()+" visible="+((JComponent)c).getVisibleRect()).toList()));
  ReportsPanel reports=WorkspaceProbe.edt(()->{var spec=new ReportSpec("DEMO-report","DEMO investigation","","",null,null,List.of());var store=new HeapLogStore(Samples.sample());var p=new ReportsPanel(()->List.of(spec),s->ReportResolver.resolve(s,store.index(),Map.of(),Set.of(),Set.of(),new FilterState()),s->null,r->{},g->{},z->{},v->{},path->{},n->{},(a,b)->null);p.refresh();return p;});show(reports,"reports-narrow",400,600);
  WorkspaceProbe.edt(()->{var selection=TemplateCatalogue.parse("{\"catalogue\":1,\"templates\":[{\"name\":\"DEMO Spring\",\"description\":\"DEMO Spring project\",\"file\":\"demo.starter.json\",\"mode\":\"aot\"},{\"name\":\"DEMO hosted\",\"description\":\"DEMO hosted processor\",\"file\":\"hosted.starter.json\",\"keyNeed\":\"build\"}]}","review fixture").forPicker();javax.swing.Timer t=new javax.swing.Timer(100,e->{for(Window w:Window.getWindows())if(w instanceof JDialog d&&d.isShowing()&&d.getTitle().equals("New project from template")){try{save(d,"template-picker");System.out.println("picker width="+d.getWidth()+" height="+d.getHeight()+" resizable="+d.isResizable());}catch(Exception ex){throw new RuntimeException(ex);}((javax.swing.Timer)e.getSource()).stop();d.dispose();}});t.start();TemplateProjectDialog.chooseTemplate(f,selection);t.stop();return null;});
 }finally{WorkspaceProbe.edt(()->{for(Window w:Window.getWindows())w.dispose();return null;});}System.exit(0);}
}
