#!/usr/bin/env python3
"""Regenerate docs/experience/current/template-spring/FQN.md from the runtime jar.

Getting an annotation's package wrong is this project's most repeated failure. The cure is not to
write the names down - a written list drifts - but to read them out of the jar every time.

usage: python3 tools/gen-fqn.py [path-to-fluxtion-runtime.jar] > FQN.md
"""
import sys, glob, os, zipfile, collections

jar = sys.argv[1] if len(sys.argv) > 1 else sorted(glob.glob(
    os.path.expanduser("~/.m2/repository/com/telamin/fluxtion/fluxtion-runtime/*/fluxtion-runtime-*.jar")))[-1]
names = [n[:-6].replace('/', '.') for n in zipfile.ZipFile(jar).namelist()
         if n.endswith('.class') and '$' not in n and not n.endswith('package-info.class')]
by_pkg = collections.defaultdict(list)
for n in (x for x in names if '.annotations.' in x):
    pkg, cls = n.rsplit('.', 1)
    by_pkg[pkg].append(cls)

out = ["# Fully-qualified names — generated from the runtime jar, not from memory", "",
       "Getting an annotation's package wrong is the single most repeated failure in this project.",
       "It is a **loud** failure (`package ... does not exist`) but it still costs a build every time.",
       "This file is generated by `tools/gen-fqn.py` reading the jar, so it cannot drift.", "",
       "```", f"generated from {os.path.basename(jar)}", "```", ""]
for pkg in sorted(by_pkg):
    out += [f"## `{pkg}`", ""] + [f"- `@{c}`" for c in sorted(by_pkg[pkg])] + [""]
extra = {
    "com.telamin.fluxtion.runtime.DataFlow": "the interface the generated processor implements",
    "com.telamin.fluxtion.runtime.audit.EventLogNode": "extend this to get an `auditLog` field",
    "com.telamin.fluxtion.runtime.audit.EventLogControlEvent": "holds `LogLevel`",
    "com.telamin.fluxtion.runtime.audit.LogRecord": "one audit record",
    "com.telamin.fluxtion.runtime.audit.LogRecordListener": "callback for records",
    "com.telamin.fluxtion.runtime.service.Service": "wrapper for `registerService`",
    "com.telamin.fluxtion.builder.extern.spring.FluxtionSpringConfig": "the bean the Spring route needs",
    "com.telamin.fluxtion.Fluxtion": "runtime build entry point (`compile`, `compileDispatcher`)",
}
present = set(names)
out += ["## Other names worth not guessing", ""]
for k, why in extra.items():
    tail = "" if k in present else "   *(builder jar, not the runtime jar)*"
    out.append(f"- `{k}` — {why}{tail}")
out += ["", "## The three that are most often confused", "",
        "| you probably want | NOT |", "|---|---|",
        "| `com.telamin.fluxtion.runtime.annotations.NoTriggerReference` | `…runtime.annotations.builder.NoTriggerReference` |",
        "| `com.telamin.fluxtion.runtime.annotations.runtime.ServiceRegistered` | `…runtime.annotations.ServiceRegistered` |",
        "| `com.telamin.fluxtion.runtime.annotations.builder.FluxtionIgnore` | `…runtime.annotations.FluxtionIgnore` |", ""]
print("\n".join(out))
