"""Mutation controls for M44.4 (the single-state session) and M68 (evidence integrity).

The witnesses behind docs/handoff/evidence/m44-4-single-state-2026-09-24/ (W3-W44 there, plus W45 here) were run by
hand from one-off scripts. That is true of a moment and protects nothing afterwards (rule 8), so they are registered
here and run by the same gate as every other control: preflight anchors, one green baseline, each mutation red at its
NAMED assertion, and a byte-identical restore that is green again.

Each entry is (name, site, old, new, 'TestClass#method'), exactly as CASES in verify_project_chart_review.py. The
anchor `old` must occur exactly once in `site`, and the preflight says so before anything runs. A regeneration that
moves a generated anchor (the GraphML edge below) fails the preflight, loudly, which is the point.
"""

J = 'src/main/java/telamin/fluxtion/audit/analyser/analyser/'
SESSION = J + 'session/'
NODE = SESSION + 'node/'
UI = J + 'ui/'
PARSE = J + 'parse/'
GRAPHML = 'src/main/resources/telamin/fluxtion/audit/analyser/analyser/session/generated/SessionProcessor.graphml'

CONTROLS = [
    # ---- M44.4a: facts replace the observation funnel
    ('m44-graph-open-is-its-own-fact', NODE + 'OpenGraph.java',
     '    public boolean isOpen() {\n        return open;', '    public boolean isOpen() {\n        return graphPath != null;',
     'SessionFactsTest#aGraphWithNoFileIsStillOpen'),
    ('m44-post-queues-mid-operation', SESSION + 'SessionDriver.java',
     '        if (dispatching) {\n            posted.add(fact);', '        if (dispatching) {\n            return;',
     'SessionFactsTest#aFactPostedMidOperationIsQueued'),
    ('m44-stale-fact-refused', NODE + 'OpenLog.java',
     '        if (named != generation) {', '        if (false) {',
     'SessionFactsTest#aStaleFactIsRefused'),
    # ---- M44.4b: one snapshot, retention by kind, no verdict in the frame
    ('m44-snapshot-published', SESSION + 'SessionDriver.java',
     '            submit(posted.poll());\n        }\n        publishSnapshot();', '            submit(posted.poll());\n        }',
     'SessionSnapshotTest#theSnapshotFollowsEachOperation'),
    ('m44-snapshot-change-only', SESSION + 'SessionDriver.java',
     '        if (next.equals(snapshot)) return;\n', '',
     'SessionSnapshotTest#listenersHearChangesOnly'),
    ('m44-graph-revision', NODE + 'OpenGraph.java',
     '        if (moved) revision++;\n', '',
     'SessionSnapshotTest#aDifferentArtefactIsADifferentPair'),
    ('m44-rescope-ring', SESSION + 'SessionAuditSink.java',
     '            } else if (kind == rescopes) {', '            } else if (false) {',
     'SessionSnapshotTest#reScopesNeverEvictTransitions'),
    ('m44-frame-computes-no-pairing', UI + 'MainFrame.java',
     '    private void reportAppendToSession() {',
     '    private Object m44Probe() { return telamin.fluxtion.audit.analyser.analyser.topology.GraphPairing.of('
     'java.util.Set.of(), java.util.Set.of()); }\n    private void reportAppendToSession() {',
     'SessionSnapshotTest#theFrameRendersAndDoesNotCompute'),
    # ---- M44.4c: the qualifications are the session's
    ('m44-rescope-keeps-qualifications', NODE + 'PairingQualifier.java',
     '        if (generation == boundGeneration && revision == boundRevision && openLog.isOpen() && openGraph.isOpen()) {',
     '        if (false) {',
     'PairingQualifierTest#aReScopeKeepsItStale'),
    ('m44-stale-comparison-refused', NODE + 'PairingQualifier.java',
     '        if (event.logGeneration() != openLog.generation() || event.graphRevision() != openGraph.revision()) {',
     '        if (false) {',
     'PairingQualifierTest#aStaleComparisonIsRefused'),
    ('m44-pending-is-the-gates', SESSION + 'SessionSnapshot.java',
     '                p.operationGate.inFlightWhat() != null,', '                false,',
     'PairingQualifierTest#aPendingOpenPublishesNoVerdict'),
    ('m44-frame-holds-no-verdict-field', UI + 'MainFrame.java',
     '    private void reportAppendToSession() {',
     '    private telamin.fluxtion.audit.analyser.analyser.topology.GraphPairing m44Field;\n'
     '    private void reportAppendToSession() {',
     'SessionSnapshotTest#theFrameRendersAndDoesNotCompute'),
    ('m44-qualifier-follows-the-pair', GRAPHML,
     'source="openLog" target="pairingQualifier"', 'source="openLog" target="nothingAtAll"',
     'SessionGraphShapeTest#theQualifierFollowsThePairAndActsOnNothing'),
    # ---- M44.4 acceptance: the M68.1 journeys, headless
    ('m44-journey-pending', SESSION + 'SessionSnapshot.java',
     '                p.operationGate.inFlightWhat() != null,', '                false,',
     'SessionLifecycleJourneysTest#aGraphOpenedDuringTheNextLoadIsJudgedAgainstTheNewLog'),
    ('m44-journey-scope', NODE + 'Pairing.java',
     '        verdict = GraphPairing.of(declared, logged).withScope(sampled, total);',
     '        verdict = GraphPairing.of(declared, logged);',
     'SessionLifecycleJourneysTest#openOrderDoesNotChangeTheVerdict'),
    ('m44-journey-stale-by-size', J + 'topology/PairingQualification.java',
     '        return logRecordsNow > logRecords;', '        return false;',
     'SessionLifecycleJourneysTest#aFollowAppendMakesTheWholeLogComparisonStale'),
    ('m44-journey-close-retires', NODE + 'PairingQualifier.java',
     '        if (generation == boundGeneration && revision == boundRevision && openLog.isOpen() && openGraph.isOpen()) {',
     '        if (generation == boundGeneration && revision == boundRevision) {',
     'SessionLifecycleJourneysTest#closingTheLogRetiresEverythingAboutIt'),
    # ---- M68.4: a combined open keeps the graph it asked for
    ('m68-4-reader-graph-not-intent', NODE + 'LogArrival.java',
     '        if (openGraph.openings() != graphOpeningsAtRequest && "OPENED".equals(openGraph.source())) {',
     '        if (openGraph.openings() != graphOpeningsAtRequest) {',
     'CombinedOpenTest#aReaderGraphIsNotIntent'),
    ('m68-4-residue-still-closed', NODE + 'LogArrival.java',
     '        if (openGraph.openings() != graphOpeningsAtRequest && "OPENED".equals(openGraph.source())) {',
     '        if ("OPENED".equals(openGraph.source())) {',
     'CombinedOpenTest#aGraphFromBeforeTheRequestIsStillResidue'),
    ('m68-4-reopen-is-intent', NODE + 'OpenGraph.java',
     '        if (moved) revision++;\n        openings++;', '        if (moved) revision++;\n        if (moved) openings++;',
     'CombinedOpenTest#reOpeningTheSameGraphIsIntent'),
    # ---- M68.5: identity under Follow, and at the next request
    ('m68-5-prefix-compared', PARSE + 'FollowIdentity.java',
     '        if (!textNow.startsWith(textRead)) {', '        if (false) {',
     'FollowIdentityTest#sameLengthRewrite'),
    ('m68-5-store-refuses-rewrite', PARSE + 'FollowIdentity.java',
     '        if (!textNow.startsWith(textRead)) {', '        if (false) {',
     'HeapLogStoreFollowIdentityTest#sameLengthRewrite'),
    ('m68-5-reopen-says-why', NODE + 'OpenLog.java',
     '        identity = reopenedAfterReplacement ? "REOPENED" : null;', '        identity = null;',
     'LogIdentityTest#aReopenAfterReplacementSaysWhy'),
    ('m68-5-moving-read-unverified', PARSE + 'FollowIdentity.java',
     '        if (changedDuringRead) {', '        if (false) {',
     'FollowIdentityTest#missingOrMoving'),
    ('m68-5-suspended-reads-refused', J + 'llm/ActionDispatcher.java',
     '        if (identity != null && identity.suspendsReads()) {', '        if (false) {',
     'ActionDispatcherReadIdentityTest#suspendedRefuses'),
    ('m68-5-in-memory-retained', PARSE + 'ReadThroughIdentity.java',
     '        if (inMemory) {', '        if (false) {',
     'ReadThroughIdentityTest#inMemoryIsRetained'),
    ('m68-5-mapped-reads-through', PARSE + 'MappedLogStore.java',
     'ReadThroughIdentity.classify(atOpen, ReadThroughIdentity.metaOf(path), false)',
     'ReadThroughIdentity.classify(atOpen, ReadThroughIdentity.metaOf(path), true)',
     'MappedLogStoreReadIdentityTest#inPlaceRewrite'),
    ('m68-5-pointer-names-root', UI + 'ProjectModel.java',
     '            String problem = str(r.get("problem"));', '            String problem = null;',
     'ProjectModelTest#aFailingPointerNamesTheRootItTried'),
    ('m68-5-resolution-names-root', J + 'config/Runbooks.java',
     'exists ? null : "no file at " + target + " (resolved against the project root " + root + ")"',
     'exists ? null : "no file at " + target',
     'RunbooksResolutionTest#notFoundNamesTheRoot'),
    # ---- M68.2: rendered evidence
    ('m68-2-chart-laid-out-at-page-size', UI + 'ChartPanel.java',
     '        setSize(w, h);\n        doLayout();\n        java.awt.image.BufferedImage img',
     '        java.awt.image.BufferedImage img',
     'ChartExportRenderTest#aNarrowChartExportsItsPlot'),
    ('m68-2-no-room-is-not-no-data', UI + 'ChartPanel.java',
     '        return "The plot has no room at this size ("',
     '        if (true) return "No data under the current filter — matched no records in view.";\n'
     '        return "The plot has no room at this size ("',
     'ChartExportRenderTest#noRoomIsNotNoData'),
    ('m68-2-not-rendered-stated', J + 'report/ReportRenderer.java',
     '                if (drawn) {\n                    picture(doc, c, body.picture());\n                } else {',
     '                if (drawn) {\n                    picture(doc, c, body.picture());\n                } else if (false) {',
     'ReportRendererTest#aChartWithNoPictureSaysItWasNotRendered'),
    # ---- M68.6: names and addresses share one grammar
    ('m68-6-quoted-compatible-address', UI + 'SpotlightTarget.java',
     '                if (rest.startsWith("\\"")) yield quotedGraph(rest, name);\n', '',
     'ChartNamingTest#everyNameHasAnAddress'),
    ('m68-6-verb-refuses-at-creation', UI + 'ActionExecutor.java',
     '                if (problem != null) return ActionResult.error("graph refused, nothing created: " + problem);',
     '                if (false) return null;',
     'ChartNamingTest#theVerbRefusesAtCreation'),
    ('m68-6-repair-applies-the-rule', J + 'config/DuplicateChartRepair.java',
     '            if (problem != null) throw new IllegalArgumentException("\'" + to + "\' cannot be used: " + problem);', '',
     'DuplicateChartRepairTest#aRepairCannotCreateANameSpotlightCannotAddress'),
    # ---- M68.4: whole or refused
    ('m68-4-rolled-set-with-graph', UI + 'ActionExecutor.java',
     '            if (!alsoOpens) {\n                return onEdt(() -> app.openLogs(paths, str(params.get("provenance"))));',
     '            if (true) {\n                return onEdt(() -> app.openLogs(paths, str(params.get("provenance"))));',
     'WholeOrRefusedTest#aRolledSetAndAGraphAreBothOpened'),
    ('m68-4-flag-never-clamps', UI + 'ActionExecutor.java',
     '            if (ri == null || ri < 0 || ri >= idx.size()) notInThisLog.add(o);\n            else rows.add(ri.intValue());',
     '            if (ri != null) rows.add(clampRow(idx, ri.intValue()));',
     'WholeOrRefusedTest#flagRefusesAnIndexTheLogDoesNotHave'),
    ('m68-4-topology-validates-first', UI + 'ActionExecutor.java',
     '        if (problem != null) return ActionResult.error(problem + " — nothing was changed");',
     '        if (problem != null && false) return null;',
     'TopologyWholeOrRefusedTest#aRefusalIsWhole'),
    ('m68-4-refusal-keeps-spotlight', UI + 'ActionExecutor.java',
     '        return changesTheView && result != null && result.ok();',
     '        return changesTheView;',
     'SpotlightEndsWhenTheViewChangesTest#aRefusedCallLeavesItLit'),
    ('m68-4-refusal-names-unknown-keys', J + 'llm/ActionDispatcher.java',
     '        if (!result.ok()) {\n            // M68.4 (D-E3): a refusal names them too.',
     '        if (!result.ok()) { if (true) return result;\n            // M68.4 (D-E3): a refusal names them too.',
     'WholeOrRefusedTest#aRefusalNamesUnknownKeys'),
    ('m68-4-goto-empty-log', UI + 'ActionExecutor.java',
     '        if (s.index().size() == 0) return ActionResult.error("this log has no records to go to");\n', '',
     'SpotlightEndsWhenTheViewChangesTest#aRefusedCallLeavesItLit'),
    # ---- M68.3: framing
    ('m68-3-quoted-key-is-text', PARSE + 'FramingScan.java',
     '            if (open == 0 && isHeader(text, headerAt, lineEnd)) {', '            if (isHeader(text, headerAt, lineEnd)) {',
     'FramingScanTest#aQuotedKeyIsText'),
    ('m68-3-legal-file-not-accused', PARSE + 'FramingScan.java',
     '            if (open == 0 && isHeader(text, headerAt, lineEnd)) {', '            if (isHeader(text, headerAt, lineEnd)) {',
     'ProducerFramingTest#aLegalOneRecordFileIsNotAccused'),
    ('m68-3-apostrophe-opens-nothing', PARSE + 'FramingScan.java',
     "                if (valuePosition && (c == '\"' || c == '\\'')) { open = c; valuePosition = false; k++; continue; }",
     "                if (c == '\"' || c == '\\'') { open = c; valuePosition = false; k++; continue; }",
     'FramingScanTest#anApostropheIsNotAQuote'),
    ('m68-3-pending-frame-scanned', PARSE + 'ProducerDiagnostics.java',
     '            pendingUnseparated(pendingFrame).ifPresent(out::add);\n', '',
     'ProducerFramingTest#aLiveCollapseIsSuspectedFromThePendingFrame'),
    # ---- independent review, 2026-09-26 (review 0bb01fa8, set 12): one control per finding, each red at its own test
    ('review-r1-capture-together', UI + 'ActionExecutor.java',
     '        CoverageInputs in = onEdt(() -> captureCoverageInputs(filtered));',
     '        CoverageInputs in = captureCoverageInputs(filtered);',
     'CoverageCaptureTest#oldInputsCannotAcquireANewIdentity'),
    ('review-r1-filter-copy', UI + 'ActionExecutor.java',
     '        FilterState copy = filtered && live != null ? live.copy() : null;',
     '        FilterState copy = filtered && live != null ? live : null;',
     'CoverageCaptureTest#theScanUsesTheFilterItCaptured'),
    ('review-r2-report-obeys-claim', J + 'report/ReportCoverage.java',
     '        if (claim != null && !claim.allowed()) {', '        if (false) {',
     'ReportCoverageTest#theArtefactStatesTheActionsRefusal'),
    ('review-r3-rolled-identity', PARSE + 'RolledLogStore.java',
     '        if (worst == null) return null;', '        if (true) return null;',
     'RolledLogStoreReadIdentityTest#aChangedMappedMemberSuspendsTheSet'),
    ('review-r4-frozen-snapshot', SESSION + 'SessionSnapshot.java',
     '        if (qualifications != null) qualifications = qualifications.frozenCopy();\n', '',
     'SessionSnapshotTest#aConsumerCannotChangeThePublishedQualifications'),
    ('review-r5-save-precheck', UI + 'ActionExecutor.java',
     '        if (params.containsKey("saveFocusAs")) {', '        if (false) {',
     'TopologyWholeOrRefusedTest#aRefusedSaveLeavesTheSelection'),
    ('review-r6-leading-bom', PARSE + 'FramingScan.java',
     "            int headerAt = i == 0 && AuditText.isBom(text.charAt(0)) ? 1 : i;   // the one BOM rule (MA, AuditText)",
     '            int headerAt = i;',
     'ProducerFramingTest#aLeadingBomDoesNotHideACollapse'),
    ('review-r7-pending-bound', PARSE + 'ProducerDiagnostics.java',
     '        if (scan.truncated()) {', '        if (false) {',
     'ProducerFramingTest#anOversizedPendingFrameIsNotAssessed'),
    ('review-r8-no-false-address', UI + 'SpotlightTarget.java',
     '        return graphAddressUnavailable(chartName) == null ? "graph:\\"" + chartName + "\\"" : null;',
     '        return "graph:\\"" + chartName + "\\"";',
     'ChartNamingTest#aSavedNameWithAQuoteHasNoAddress'),
    ('review-r8-series-not-rendered', J + 'report/ReportRenderer.java',
     '                    callout(doc, c, "NOT RENDERED", "series section: "',
     '                    callout(doc, c, "Series", "series section: "',
     'ReportRendererTest#anUnassembledSeriesSectionSaysNotRendered'),
    ('review-o1-ordered-delivery', SESSION + 'SessionDriver.java',
     '            if (snapshot != next) return;\n', '',
     'SessionSnapshotTest#aListenerThatPostsDoesNotReorderDelivery'),
    ('review-r2-frame-asks-the-helper', UI + 'MainFrame.java',
     '        return telamin.fluxtion.audit.analyser.analyser.report.ReportCoverage.forReport(\n                store, input, sessionSnapshot().claim(), filtered, filter);',
     '        return input == null ? null : new telamin.fluxtion.audit.analyser.analyser.report.ReportVerb.CoverageData(\n                java.util.List.of(), telamin.fluxtion.audit.analyser.analyser.topology.CoverageService.assess(store, filtered, filter, input).scalarLine(), java.util.List.of(), null);',
     'ReportCoverageTest#theFrameDoesNotDecideCoverageForAReport'),
    # ---- set 13 (owner request, 2026-09-26): the stated gaps closed before one review
    ('set13-a-table-banner', UI + 'LogTablePanel.java',
     '        if (!"UNVERIFIED".equals(verdict) && !"REPLACEMENT".equals(verdict)) return null;',
     '        if (true) return null;',
     'LogTablePanelIdentityBannerTest#theBannerStatesOnlyAChange'),
    ('set13-a-rendered-from-snapshot', UI + 'MainFrame.java',
     '        tablePanel.setIdentityNote(LogTablePanel.identityBannerText(next.logIdentity(), next.logIdentityReason()));\n',
     '',
     'LogTablePanelIdentityBannerTest#theFrameRendersItFromTheSnapshot'),
    ('set13-b-focus-drawn', UI + 'TopologyPanel.java',
     '        if (resolved.isEmpty()) return null;', '        if (true) return null;',
     'TopologyReportFocusTest#aSavedFocusRenders'),
    ('set13-c-series-drawn', UI + 'ReportSeriesPicture.java',
     '        if (image == null) return Result.problem("the chart produced no picture");',
     '        if (true) return Result.problem("the chart produced no picture");',
     'ReportSeriesPictureTest#aKeySeriesIsDrawn'),
    ('set13-d-directory-checked', J + 'config/Runbooks.java',
     '        boolean exists = Files.isDirectory(target);', '        boolean exists = true;',
     'RunbooksResolutionTest#aDirectoryPointerIsDiagnosed'),
    ('set13-e-nested-keys', J + 'llm/ActionDispatcher.java',
     '            if (props.get(e.getKey()) instanceof Map<?, ?> prop) nested(e.getKey(), e.getValue(), prop, ignored);\n',
     '',
     'ActionDispatcherNestedKeysTest#aNestedUnknownKeyIsNamed'),
    ('set13-chart-series-agree', J + 'graph/SeriesScan.java',
     '            count++;\n            sum += v;', '            count += 2;\n            sum += v;',
     'ChartSeriesAgreementTest#theChartAndTheSeriesVerbCountTheSamePoints'),
    # ---- re-review 2026-09-26 (93046a48, set 14): N1 and N2
    ('review-n1-showall-in-preparation', UI + 'ActionExecutor.java',
     '        if (params.containsKey("showAll") && bool(params.get("showAll"))) t.showAll();',
     '        if (params.containsKey("showAll") && bool(params.get("showAll")) && t == topology) t.showAll();',
     'TopologyWholeOrRefusedTest#aRefusedSaveAfterShowAllLeavesTheExistingFocus'),
    ('review-n2-report-forces-locf', UI + 'ReportSeriesPicture.java',
     '                    parsed.resolve());', '                    SeriesExtractor.Resolve.LOCF);',
     'ReportSeriesCallTest#aStrictCallIsNotCarried'),
    ('review-n2-report-drops-call-filter', UI + 'ReportSeriesPicture.java',
     '                    parsed.filter(),',
     '                    new telamin.fluxtion.audit.analyser.analyser.filter.FilterState(),',
     'ReportSeriesCallTest#theCallFilterIsHonoured'),
    ('review-n2-report-literal-key', J + 'graph/SeriesScan.java',
     '        Expr expr = literalKey == null ? Expr.parse(exprText.toString()) : new Expr.Ref(literalKey);',
     '        Expr expr = Expr.parse(exprText.toString());',
     'ReportSeriesCallTest#aLiteralKeyNeverBecomesAFormula'),
    # ---- phase-1 completion (D-MA0c, MA-0.5, MA-8's report path, MA-6.3) and its review, 2026-09-26. The first eight
    # were witness15.py's, run once by hand (docs/handoff/evidence/mongoose-audit-production-impl/phase1-completion/);
    # registered here so they protect the code rather than record one run.
    ('p15-pdf-log-findings-callout', J + 'report/ReportRenderer.java',
     '        if (logFindings != null && !logFindings.isClean()) {',
     '        if (logFindings != null && !logFindings.isClean() && false) {',
     'ReportLogFindingsTest#theLogsFindingsAreOnThePdf_damageFirst'),
    ('p15-report-reply-producer', UI + 'MainFrame.java',
     '            echo.put("producer", producer.messages());',
     '            // echo.put("producer", producer.messages());',
     'LogFindingsOnEverySurfaceFrameTest#anEmptyFollowedFileSaysSoEverywhere_andEverySurfaceClearsWhenARecordArrives'),
    ('p15-reports-tab-banner', UI + 'ReportsPanel.java',
     '        if (findings != null && !findings.isClean()) {',
     '        if (findings != null && !findings.isClean() && false) {',
     'LogFindingsOnEverySurfaceFrameTest#anEmptyFollowedFileSaysSoEverywhere_andEverySurfaceClearsWhenARecordArrives'),
    ('p15-follow-line-keeps-warning', UI + 'MainFrame.java',
     'orderWarning(order), producerWarning(findings), trailingPendingNote());',
     'orderWarning(order), "", trailingPendingNote());',
     'LogFindingsOnEverySurfaceFrameTest#anEmptyFollowedFileSaysSoEverywhere_andEverySurfaceClearsWhenARecordArrives'),
    ('p15-ledger-level-change', J + 'topology/CoverageService.java',
     'if (note != null && "uncovered".equals(row.get("status"))) row.put("levelChange", note);',
     'if (note != null && "uncovered".equals(row.get("status"))) { }',
     'ReportLogFindingsTest#aReportsCoverageRowCarriesTheLevelChange_andStaysUncovered'),
    ('p15-c25-empty-log-raised', PARSE + 'ProducerDiagnostics.java',
     '        if (idx.size() == 0 && !pending) {',
     '        if (idx.size() == 0 && !pending && false) {',
     'FormatConformanceTest#c25_aMarkerDeclaringZeroIsCompleteAndStillAnEmptyLog'),
    ('p15-c29-no-record-key-raised', PARSE + 'ProducerDiagnostics.java',
     '        noRecordKey(idx, rawText).ifPresent(out::add);',
     '        // noRecordKey(idx, rawText).ifPresent(out::add);',
     'FormatConformanceTest#c29_aCompleteFileCanStillHoldADocumentWithNoRecordKey'),
    ('p15-c30-control-event-parse', J + 'topology/PerNodeLevelChanges.java',
     '        return telamin.fluxtion.audit.analyser.analyser.parse.ProducerDiagnostics.isControlEvent(event);',
     '        return false;',
     'FormatConformanceTest#c30_aPerNodeLevelChangeAnnotatesTheSameNodeOnBothPaths'),
    # ---- the review's survivors (H1-H4) and the optional items' controls
    ('p16-h1-frame-pdf-gets-findings', UI + 'MainFrame.java',
     '                store == null ? null : sessionSnapshot().producerFindings());   // D-MA0c: the log\'s findings are on the page',
     '                null);',
     'LogFindingsOnEverySurfaceFrameTest#theExportedPdfCarriesTheLogsFindings_andLosesThemWhenARecordArrives'),
    ('p16-h2-tab-refresh-on-load', UI + 'MainFrame.java',
     # M44.5: the load and the Follow refresh are one render now; both controls anchor it, each at its own witness
     '        if (findingsMoved && reportsPanel != null) reportsPanel.refresh();', '',
     'LogFindingsOnEverySurfaceFrameTest#theTabIsCurrentAfterASecondLogLoads_withNoVerbInBetween'),
    ('p16-h3-tab-refresh-on-follow', UI + 'MainFrame.java',
     '        if (findingsMoved && reportsPanel != null) reportsPanel.refresh();', '',
     'LogFindingsOnEverySurfaceFrameTest#theTabIsCurrentAfterAFollowPoll_withNoVerbInBetween'),
    ('p16-h4-level-change-on-every-row', J + 'topology/CoverageService.java',
     'String note = annotations.get(String.valueOf(row.get("instanceId")));',
     'String note = annotations.isEmpty() ? null : annotations.values().iterator().next();',
     'CoveragePerNodeLevelTest#levelChangesNeverMoveTheDenominatorOrTheLedger'),
    ('p16-v2-pending-frame-is-not-empty', PARSE + 'ProducerDiagnostics.java',
     '        if (idx.size() == 0 && !pending) {', '        if (idx.size() == 0) {',
     'LogFindingsOnEverySurfaceFrameTest#aRecordStillBeingWrittenIsNotAnEmptyFile'),
    ('p16-wording-marker-says-ended', PARSE + 'ProducerDiagnostics.java',
     '        if (streamEnd != null && streamEnd.state() == StreamEnd.State.COMPLETE && streamEnd.declaredRecords() == 0) {',
     '        if (false) {',
     'FormatConformanceTest#c25_aMarkerDeclaringZeroIsCompleteAndStillAnEmptyLog'),
    ('p16-wording-rolled-set', PARSE + 'ProducerDiagnostics.java',
     '        if (idx.fileCount() > 1) {', '        if (false) {',
     'EmptyLogAndRecordKeyDiagnosticsTest#aRolledSetOfEmptyMembersIsNamedAsASet'),
    ('p16-tab-note-only-muted', UI + 'ReportsPanel.java',
     '            detail.add(findings.firstWarning().isPresent() ? banner(label, body, null, null) : noteBanner(label, body));',
     '            detail.add(banner(label, body, null, null));',
     'ReportsPanelLogFindingsTest#aNoteOnlySetIsDrawnMuted_likeThePdf'),
    # ---- targeted re-review of PR #40: V2 at both call sites that word the empty-log finding. X4 named the Follow site
    # as `store.streamEnd()`; optional 2 moved both sites to emptyLogClaim(), so X4 is the same mutation on that text.
    ('p17-v2-follow-passes-stream-end', UI + 'MainFrame.java',
     # M44.5: the Follow and load sites are logEvidence's one scan; each control keeps its own witness
     's.emptyLogClaim());', 'null);',
     'LogFindingsOnEverySurfaceFrameTest#aFollowedFileThatGainsAZeroMarkerSaysWhatAColdOpenSays'),
    ('p17-cold-open-passes-stream-end', UI + 'MainFrame.java',
     's.emptyLogClaim());', 'null);',
     'LogFindingsOnEverySurfaceFrameTest#aColdOpenOfAFileWhoseMarkerSaysItEndedSaysSo'),
    ('p17-one-member-set-is-its-file', PARSE + 'RolledLogStore.java',
     '        return members.size() == 1 ? members.get(0).streamEnd() : streamEnd();', '        return streamEnd();',
     'EmptyLogAndRecordKeyDiagnosticsTest#aOneMemberRolledSetIsWordedAsItsFile'),
    # R2 (X5): the LOAD site, through the frame. The Follow site owes no control: only HeapLogStore follows, and its
    # emptyLogClaim() IS its streamEnd(), so reverting that site is an equivalent mutation (the reviewer's X6).
    ('p18-one-member-set-at-load-site', UI + 'MainFrame.java',
     's.emptyLogClaim());', 's.streamEnd());',
     'LogFindingsOnEverySurfaceFrameTest#aOneMemberSetOpenedInTheFrameIsWordedAsItsFile'),
    # ---- M68.7 (owner, Q4 2026-09-26): the charts and the detail pane state the file-identity verdict
    ('m68-7-charts-not-rendered', UI + 'MainFrame.java',
     '        graphTabs.setIdentityNote(GraphTabs.identityBannerText(next.logIdentity(), next.logIdentityReason()));\n',
     '',
     'IdentityMarkFrameTest#anInPlaceRewriteIsStatedOnTheTableTheChartsAndTheDetailPane'),
    ('m68-7-detail-not-rendered', UI + 'MainFrame.java',
     '        detailPanel.setIdentityNote(DetailPanel.identityBannerText(next.logIdentity(), next.logIdentityReason()));\n',
     '',
     'IdentityMarkFrameTest#anInPlaceRewriteIsStatedOnTheTableTheChartsAndTheDetailPane'),
    ('m68-7-chart-banner-hidden', UI + 'GraphTabs.java',
     '        identityBanner.setVisible(note != null);\n        revalidate();\n    }\n\n    /** The banner\'s text, or null while it is hidden. */',
     '        identityBanner.setVisible(false);\n        revalidate();\n    }\n\n    /** The banner\'s text, or null while it is hidden. */',
     'IdentityMarkSurfacesTest#theBannersAreOnThePanels'),
    ('m68-7-chart-text-bypasses-rule', UI + 'GraphTabs.java',
     '        if (LogTablePanel.identityBannerText(verdict, reason) == null) return null;\n',
     '',
     'IdentityMarkSurfacesTest#theSurfacesShareTheTablesRule'),
    # ---- M68.7 review (34f4d800) R1: the mark must reach the SCREEN, not only the label's own flag; O2: theme colour
    ('m68-7-chart-banner-detached', UI + 'GraphTabs.java',
     '        north.add(identityBanner, BorderLayout.SOUTH);\n', '',
     'IdentityMarkFrameTest#anInPlaceRewriteIsStatedOnTheTableTheChartsAndTheDetailPane'),
    ('m68-7-detail-banner-detached', UI + 'DetailPanel.java',
     '        north.add(identityBanner, BorderLayout.SOUTH);\n', '',
     'IdentityMarkFrameTest#anInPlaceRewriteIsStatedOnTheTableTheChartsAndTheDetailPane'),
    ('m68-7-chart-colour-fixed-at-construction', UI + 'GraphTabs.java',
     '            super.updateUI();\n            setForeground(UiTheme.warnForeground());\n', '            super.updateUI();\n',
     'IdentityMarkSurfacesTest#theWarningColourFollowsTheTheme'),
    # ---- M44.5: the log's own evidence is the session's (logEvidence), and one dispatch model holds it there
    ('m44-5-stale-evidence-refused', NODE + 'LogEvidence.java',
     '        if (named != openLog.generation()) {', '        if (false) {',
     'LogEvidenceTest#aStaleResultIsRefused'),
    ('m44-5-marker-moves-the-signature', NODE + 'LogEvidence.java',
     ' + "/" + event.streamEnd()', '',
     'LogEvidenceTest#theContentSignatureDecidesARescan'),
    ('m44-5-append-is-outstanding-at-once', NODE + 'LogEvidence.java',
     '        requestScan(event.generation(), "records appended");', '',
     'LogEvidenceTest#anAppendIsOutstandingEvidenceAtOnce'),
    ('m44-5-follow-only-where-it-can-run', NODE + 'OpenLog.java',
     '        following = following && event.followable();', '        following = following;',
     'LogEvidenceTest#followSurvivesAReloadOnlyWhereItCanRun'),
    ('m44-5-observations-own-ring', SESSION + 'SessionAuditSink.java',
     '            if (kind == observations) {', '            if (false) {',
     'SessionSnapshotTest#idlePollsEvictNothingButTheirOwnKind'),
    # W1: the frame test sees the time order the scan derives — a scan that validates nothing leaves it unreported
    ('m44-5-w1-follow-validates-time-order', UI + 'MainFrame.java',
     'TimeOrderValidator.validate(s);', 'TimeOrderReport.clean();',
     'LogFindingsOnEverySurfaceFrameTest#aTimeOrderViolationAppendedUnderFollowIsReported'),
    # W2: the Follow line drops the provenance again, as its second assembly did
    ('m44-5-w2-follow-line-keeps-provenance', UI + 'MainFrame.java',
     '                next.provenance() != null ? next.provenance()',
     '                next.provenance() != null && !next.following() ? next.provenance()',
     'LogFindingsOnEverySurfaceFrameTest#theFollowLineKeepsTheProvenanceAndTheOrderWarning'),
    ('m44-5-line-waits-for-the-session', UI + 'MainFrame.java',
     '        if (next.total() != s.size()) return;', '',
     'LogFindingsOnEverySurfaceFrameTest#theLineNeverCountsNewRowsBesideTheOldFindings'),
    ('m44-5-line-waits-for-the-scan', UI + 'MainFrame.java',
     'next.evidencePending()', 'false',
     'LogFindingsOnEverySurfaceFrameTest#theLineNeverCountsNewRowsBesideTheOldFindings'),
    # acceptance 4: the environment's provenance is resolved BEFORE the log is reported open, into the one copy
    ('m44-5-environment-before-open', UI + 'MainFrame.java',
     '                provenance = match.environment().provenance();\n', '',
     'LogFindingsOnEverySurfaceFrameTest#anEnvironmentsProvenanceIsTheSessionsAndEverySurfaceStatesIt'),
    # ---- PR #43 review: F1 (a dropped scan swallowed every later generation's), F2 (the set's cross-file order rides
    # with its store), F3 (the static check's text-matching gaps)
    ('m44-5-f1-new-generation-resets-outstanding', NODE + 'LogEvidence.java',
     '        scanPending = false;\n        boundGeneration = generation;', '        boundGeneration = generation;',
     'LogEvidenceTest#aDroppedScanDoesNotSwallowTheNextGenerationsScan'),
    ('m44-5-f1-frame-next-log-is-scanned', NODE + 'LogEvidence.java',
     '        scanPending = false;\n        boundGeneration = generation;', '        boundGeneration = generation;',
     'LogFindingsOnEverySurfaceFrameTest#aLoadThatThrowsPartWayDoesNotStopTheNextLogsEvidence'),
    ('m44-5-f2-set-carries-its-cross-file-order', UI + 'MainFrame.java',
     'files, config.memoryThresholdMb, set.report());', 'files, config.memoryThresholdMb, null);',
     'LogFindingsOnEverySurfaceFrameTest#aRolledSetsFileOverlapReachesContextAndTheLine'),
    ('m44-5-f2-validation-merges-the-cross-file-part', PARSE + 'TimeOrderValidator.java',
     '        return crossFile == null ? order : crossFile.merged(order);', '        return order;',
     'TimeOrderValidatorTest#aRolledSetsCrossFileOverlapIsPartOfItsTimeOrder'),
    ('m44-5-f3-generic-copy', UI + 'MainFrame.java',
     '    private void reportAppendToSession() {',
     '    private java.util.Optional<telamin.fluxtion.audit.analyser.analyser.parse.TimeOrderReport> m445Copy;\n'
     '    private void reportAppendToSession() {',
     'OneDispatchModelTest#noSurfaceHoldsACopy'),
    ('m44-5-f3-follow-line-in-poll', UI + 'MainFrame.java',
     '        reportContentToSession(null);              // W1',
     '        status.setText("Following " + displayName(followPath));\n'
     '        reportContentToSession(null);              // W1',
     'OneDispatchModelTest#theLogLineHasOneComposer'),
    ('m44-5-f3-method-reference', UI + 'MainFrame.java',
     '        String pending = store.pendingFrameText();',
     '        java.util.function.Function<LogStore, telamin.fluxtion.audit.analyser.analyser.parse.TimeOrderReport> m445Ref'
     ' = telamin.fluxtion.audit.analyser.analyser.parse.TimeOrderValidator::validate;\n'
     '        String pending = store.pendingFrameText();',
     'OneDispatchModelTest#everyDerivedStepHasOneHome'),
    ('m44-5-f3-timer-stopped-outside-render', UI + 'MainFrame.java',
     '        renderFollowControls(following());\n        if (entering',
     '        renderFollowControls(following());\n        if (followTimer != null) followTimer.stop();\n        if (entering',
     'OneDispatchModelTest#everyDerivedStepHasOneHome'),
    # the static check: a derived step at a second call site, and a frame copy of the evidence
    ('m44-5-static-second-call-site', UI + 'MainFrame.java',
     '        String pending = store.pendingFrameText();',
     '        var m445Probe = telamin.fluxtion.audit.analyser.analyser.parse.TimeOrderValidator.validate(store.index());\n'
     '        String pending = store.pendingFrameText();',
     'OneDispatchModelTest#everyDerivedStepHasOneHome'),
    ('m44-5-static-frame-copy', UI + 'MainFrame.java',
     '    private void reportAppendToSession() {',
     '    private telamin.fluxtion.audit.analyser.analyser.parse.ProducerDiagnostics producerDiagnostics;\n'
     '    private void reportAppendToSession() {',
     'OneDispatchModelTest#noSurfaceHoldsACopy'),
    # ---- PR #33 review fixes (2026-09-27): D-2's real-path check, and the recoverable report delete
    ('p33-exchange-link-escape', J + 'config/ExchangeDir.java',
     '            if (!real.startsWith(realRoot)) {', '            if (false) {',
     'ProjectSuppliedExchangeDirTest#aLinkOutOfTheProjectIsRefused'),
    ('p33-delete-skips-the-bin', J + 'config/ReportBin.java',
     '        c.deletedReports.add(0, new DeletedReport(projectKey(c), now, doomed));\n', '',
     'ReportBinTest#deleteThenRestoreRoundTripsThroughPersistence'),
    ('p33-bin-not-saved', J + 'config/ConfigStore.java',
     '        writeDeletedReports(p, c.deletedReports);   // always the machine\'s: the bin is not project state\n', '',
     'ReportBinTest#theMachineSettingsSaveKeepsTheBin'),
    ('p33-restore-ignores-project', J + 'config/ReportBin.java',
     '            if (d.project().equals(key) && d.report().name().equals(name)) { found = d; break; }',
     '            if (d.report().name().equals(name)) { found = d; break; }',
     'ReportBinTest#restoreIsScopedToTheProject'),
    ('p33-restore-not-routed', UI + 'ActionExecutor.java',
     '|| params.containsKey("csv") || params.containsKey("restore")) {', '|| params.containsKey("csv")) {',
     'ReportRecoverableDeleteFrameTest#theAssistantsDeleteCanBeUndone'),
    ('p33-nested-link-containment', J + 'llm/ExportGuard.java',
     '            if (!realTarget.startsWith(realDir)) {', '            if (false) {',
     'ReportRecoverableDeleteFrameTest#aProjectExchangeCannotExportThroughANestedOutsideLink'),
    ('p33-canonical-exchange-location', J + 'config/ExchangeDir.java',
     '            return new ExchangeDir(real.toString(), PROJECT, null);',
     '            return new ExchangeDir(resolved.toString(), PROJECT, null);',
     'ProjectSuppliedExchangeDirTest#anAcceptedAliasReturnsItsCheckedLocation'),
    ('p33-absolute-alias-paths', J + 'llm/ExportGuard.java',
     '    private static Resolved containedTarget(Path dir, Path resolved) {\n',
     '    private static Resolved containedTarget(Path dir, Path resolved) {\n'
     '        if (!resolved.startsWith(dir)) return new Resolved(null, "path is outside the exchange directory");\n',
     'ExportGuardTest#absoluteAliasRequestsUseTheCanonicalExchangeLocation'),
    ('p33-canonical-export-target', J + 'llm/ExportGuard.java',
     '            return new Resolved(realTarget, null);', '            return new Resolved(resolved, null);',
     'ExportGuardTest#anInternalLinkAllowsNewDescendantsAndReturnsTheCheckedLocation'),
    ('p33-restore-string-true', UI + 'MainFrame.java',
     '            if (Boolean.TRUE.equals(restore)) {',
     '            if (Boolean.TRUE.equals(restore) || "true".equals(String.valueOf(restore))) {',
     'ReportRecoverableDeleteFrameTest#aReportNamedTrueIsRestoredRatherThanListed'),
    ('p33-restore-mixed-operations', UI + 'ActionExecutor.java',
     '                    if (params.size() != 1) return ActionResult.error("report \'restore\' must be used alone");\n', '',
     'ReportRecoverableDeleteFrameTest#restoreRefusesMixedOperationsWithoutChangingAnything'),
    ('p33-visible-report-actions', UI + 'ReportsPanel.java',
     '        JPanel bar = new JPanel(new java.awt.GridLayout(0, 1, 0, 4));',
     '        JPanel bar = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 2));',
     'ReportRecoverableDeleteFrameTest#theVisibleButtonsDeleteRestoreAndExplainAnEmptyBin'),
    ('p33-restore-schema', J + 'llm/VerbSchemas.java',
     'new java.util.LinkedHashMap<>(Map.of("anyOf", List.of(string(), Map.of("type", "boolean", "enum", List.of(true)))))',
     'string()', 'VerbSchemasTest#reportRestorePublishesBothNamesAndTheBooleanListRequest'),
    # ---- PR #51 (chart and report lifecycle, #46–#50 + spotlight) and its review: each fix at its CALL SITE, not only
    # its helper — the review found every call-site removal left the PR's own tests green
    ('p51-46-verb-merges', UI + 'MainFrame.java',
     'var spec = parsed.onto(existing);', 'var spec = parsed.spec();',
     'ReportRecoverableDeleteFrameTest#aRetitleThroughTheVerbKeepsTheSectionsAndSaysWhichLogTheyWereWrittenAgainst'),
    ('p51-46-written-against', UI + 'MainFrame.java',
     'echo.put("writtenAgainst", (spec.fingerprint() != null ? spec.fingerprint() : fp).describe());',
     'echo.put("writtenAgainst", fp.describe());',
     'ReportRecoverableDeleteFrameTest#aRetitleThroughTheVerbKeepsTheSectionsAndSaysWhichLogTheyWereWrittenAgainst'),
    ('p51-46-absent-keeps', J + 'report/ReportVerb.java',
     'boolean keepSections = !supplied.contains("sections");', 'boolean keepSections = false;',
     'AbsentSectionsMeanUnchangedTest#retitleKeepsSections'),
    ('p51-47-notes-replace', UI + 'ActionExecutor.java',
     '            before = notes.notes().size();\n            notes = notes.withoutNotes();',
     '            before = notes.notes().size();',
     'GraphNotesReplaceAndChartsDeleteTest#notesReplaceOnResend'),
    ('p51-47-dropped-notes-named', UI + 'ActionExecutor.java',
     '        if (p.get("notes") instanceof List<?> && !dropped.isEmpty()) {', '        if (false) {',
     'GraphNotesReplaceAndChartsDeleteTest#droppedNotesAreNamed'),
    ('p51-48-labels-painted', UI + 'ChartPanel.java',
     'int labelBaseline = axisLabelBaseline(plotY, plotH);', 'int labelBaseline = h - 6;',
     'ChartDrawsItsClosingValueTest#theAxisLabelsArePaintedWithANote'),
    ('p51-49-hold-exact-path', UI + 'ChartPanel.java',
     '        holdToWindowEdge(g, prevX, prevY, have);\n    }\n\n    /**\n     * #49', '    }\n\n    /**\n     * #49',
     'ChartDrawsItsClosingValueTest#theHoldIsPainted'),
    ('p51-49-hold-decimated-path', UI + 'ChartPanel.java',
     '        holdToWindowEdge(g, prevX, prevY, have);   // #49, and the javadoc above says why it must match\n', '',
     'ChartDrawsItsClosingValueTest#theHoldIsPainted'),
    ('p51-49-trailing-gap', UI + 'ChartPanel.java',
     '        if (s.size() > 0 && !Double.isFinite(s.y(s.size() - 1))) have = false;\n', '',
     'ChartDrawsItsClosingValueTest#aTrailingGapIsNotHeld'),
    ('p51-50-delete-first', UI + 'ActionExecutor.java',
     '        if (bool(p.get("delete"))) {\n            // #50', '        if (false) {\n            // #50',
     'GraphNotesReplaceAndChartsDeleteTest#deleteDoesNotFallThroughToTheBuildPath'),
    ('p51-50-closed-chart', UI + 'GraphTabs.java',
     '        if (!hasDefinition(target)) return false;\n        deleteListener.accept(target);',
     '        if (!hasDefinition(target)) return false;\n        if (true) return true;\n        deleteListener.accept(target);',
     'GraphNotesReplaceAndChartsDeleteTest#aClosedChartCanBeDeleted'),
    ('p51-50-last-chart-leaves-none', UI + 'GraphTabs.java',
     '            if (placeholder != null) placeholders.add(placeholder);\n', '',
     'GraphNotesReplaceAndChartsDeleteTest#deletingTheLastChartLeavesNoneBehind'),
    ('p51-spotlight-slides', UI + 'SpotlightGeometry.java',
     'private static final int[] SLIDE_STEPS = {1, -1, 2, -2};', 'private static final int[] SLIDE_STEPS = {};',
     'SpotlightCalloutsDoNotCollideTest#fourAdjacentLinesDoNotCollide'),

    # --- PR #51 review response -------------------------------------------------------------------
    # An explicit null must read as ABSENT. containsKey made "sections": null wipe the report — #46's
    # own defect, reached by the route a JSON client takes when an optional has no value.
    ('p51r-46-null-is-absent', J + 'report/ReportVerb.java',
     'if (params.get(key) != null) supplied.add(key);', 'if (params.containsKey(key)) supplied.add(key);',
     'AbsentMeansAbsentTest#nullSectionsIsAbsent'),

    # createdAt follows the SECTIONS, like the fingerprint and filter beside it. Keeping the old date
    # on a full replace printed CREATED and WRITTEN AGAINST describing two different reports.
    ('p51r-46-createdat-follows-sections', J + 'report/ReportVerb.java',
     'keepSections ? existing.createdAt() : spec.createdAt(),', 'existing.createdAt(),',
     'AbsentMeansAbsentTest#replacedSectionsTakeTodaysDate'),

    # close is the safe half of removal. Without it, delete was the only way to get a chart off the
    # screen over the socket, so "not recoverable" was not advice a caller could act on.
    ('p51r-50-close-keeps-definition', UI + 'GraphTabs.java',
     'gp.unbind();\n        tabs.removeTabAt(indexOf(gp));\n        fireChanged();\n        return null;',
     'deleteListener.accept(name.trim());\n        gp.unbind();\n        tabs.removeTabAt(indexOf(gp));\n        fireChanged();\n        return null;',
     'GraphNotesReplaceAndChartsDeleteTest#closeKeepsWhatDeleteRemoves'),

    # A delete under a definition refusal must not write to the profile. The UI disables Delete
    # wholesale; the socket refuses only withheld names, and this is what makes that safe.
    # Second review: the old assertion here was a liveness check. `definitions::remove` cannot fail for a
    # name that was never in the list, so "the saved list survived" held however the delete behaved. The
    # witness is now WHICH name reached the profile's removal channel, and this control is what proves it.
    ('p51r-50-delete-names-the-right-chart', UI + 'GraphTabs.java',
     'deleteListener.accept(name);\n        if (tabs.getTabCount() == 0) {',
     'deleteListener.accept(name + "-WRONG");\n        if (tabs.getTabCount() == 0) {',
     'ChartDeleteUnderDefinitionRefusalTest#aChartWithNoSavedDefinitionMayGo'),

    ('p51r-50-refusal-guard', UI + 'ActionExecutor.java',
     'boolean withheld = target == null || onEdt(() -> graphTabs.isWithheldDefinition(target));',
     'boolean withheld = false;',
     'ChartDeleteUnderDefinitionRefusalTest#aWithheldChartIsRefused'),

    # Reviewer, on the response: close promises "kept", and under a definition refusal nothing is saved —
    # so a close there discarded the chart while saying it had kept it. The refusal keeps the promise true.
    ('p51r-50-close-refused-under-refusal', UI + 'GraphTabs.java',
     '        if (definitionRefusal != null) {\n            return "\'" + name.trim() + "\' is not saved',
     '        if (false) {\n            return "\'" + name.trim() + "\' is not saved',
     'ChartDeleteUnderDefinitionRefusalTest#aCloseUnderRefusalWouldDiscardSoItIsRefused'),

    # Reviewer, on the response: the guidance an assistant reads. "Close its tab" named a gesture a socket
    # caller cannot make, and "close ... for tidying up" sent probes into the profile — a closed chart keeps
    # its definition, which is the accumulation #50 exists to stop.
    ('p51r-50-guidance-names-the-verb', J + 'llm/VerbSchemas.java',
     'to put a chart away without losing it, use close instead")',
     'to put a chart away without losing it, close its tab instead")',
     'ChartRemovalGuidanceTest#closeIsTheVerbNotATab'),
    ('p51r-50-guidance-probes-are-deleted', J + 'llm/VerbSchemas.java',
     '"definition — for a chart worth keeping; a closed probe still sits in the "\n                                + "profile, so delete those. Goes alone; refused for the last open chart"',
     '"definition — the safe half of removal, and what to use when tidying up. "\n                                + "Goes alone; refused for the last open chart"',
     'ChartRemovalGuidanceTest#closeIsNotHowProbesAreCleanedUp'),

    # PR #51 CI (run 36332664650): a source pane read from a test thread raced the EDT's replacement of its document,
    # and getText() answered null. The test accessors read on the EDT; without that, the witness sees an instant answer.
    ('p51ci-pane-text-read-on-edt', UI + 'SourcePanel.java',
     'if (SwingUtilities.isEventDispatchThread()) return read.get();', 'if (true) return read.get();',
     'SourcePanelPaneTextIsReadOnTheEdtTest#paneTextWaitsForTheEdt'),

    # --- M69 spotlight walks -------------------------------------------------------------------------------------
    # S0 (review R5): the graph digest belongs to the graph shown. Without the reset, clearing a file graph leaves its
    # digest behind to describe whatever is shown next.
    ('m69-s0-clear-drops-graph-digest', UI + 'TopologyPanel.java',
     '        forgetGraphIdentity();   // M69 S0 (R5): no graph is shown, so no digest may describe one\n', '',
     'TopologyGraphDigestTest#clearDropsTheDigest'),
]
